name = "SignedDistanceFunctions"
uuid = "855ad1b6-2dea-42ad-aaa8-ce6615455336"
authors = ["Zoe McCarthy <zoemccarthy12@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
CoordinateTransformations = "0.6"
FiniteDifferences = "0.11"
ForwardDiff = "0.10"
GeometryBasics = "0.3"
Rotations = "1.0"
StaticArrays = "1.0"
Zygote = "0.5, 0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
